# Generated by Django 3.1.2 on 2021-04-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='detail',
        ),
        migrations.AddField(
            model_name='item',
            name='asin',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.TextField(default='', editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(default='', editable=False, max_length=500),
        ),
    ]
