# Generated by Django 3.1.2 on 2021-04-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0003_auto_20210419_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='last_name',
        ),
        migrations.AddField(
            model_name='item',
            name='asin',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
