# Generated by Django 3.1.2 on 2021-04-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0004_auto_20210419_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='asin',
            field=models.TextField(default='', editable=False, max_length=100),
        ),
    ]
