# Generated by Django 3.1.2 on 2021-04-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0006_auto_20210419_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='asin',
            field=models.CharField(default='', max_length=100),
        ),
    ]
