# Generated by Django 3.1.2 on 2021-04-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0007_item_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reviewText',
            field=models.TextField(default='', max_length=500),
        ),
    ]
