# Generated by Django 3.1.2 on 2021-04-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0011_auto_20210419_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.TextField(default='', max_length=500),
        ),
    ]
