# Generated by Django 3.1.2 on 2021-04-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0012_auto_20210419_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.JSONField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='reviewText',
            field=models.JSONField(default='', max_length=5000),
        ),
    ]
