# Generated by Django 3.1.2 on 2021-04-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0013_auto_20210419_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='reviewText',
            field=models.JSONField(),
        ),
    ]
