# Generated by Django 3.1.2 on 2021-04-20 00:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0014_auto_20210419_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='', max_length=500), size=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='reviewText',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='', max_length=500), size=None),
        ),
    ]
