# Generated by Django 3.1.2 on 2021-04-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0015_auto_20210419_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='reviewText',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
